# -*- coding: utf-8 -*-
"""MainPipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAnOi3HKKgZmqRw3piozYXPY-x8FBI-Q
"""

import os
import pandas as pd
from utils import compute_final_cpi, save_geojson_with_cpi, generate_cpi_map

# ================== CONFIG ==================
# Define paths
csv_path = "/n/netscratch/cga/Lab/rpalbuquerque/CPI/cpi_por_setor_2020_dez.csv"
geojson_path = "/n/home03/rpereiraalbuquerque/shapes/municipios_simplificados.geojson"
out_csv = "/n/netscratch/cga/Lab/rpalbuquerque/CPI/cpi_final_setores_2020_dez.csv"
out_geojson = "/n/netscratch/cga/Lab/rpalbuquerque/CPI/setores_com_CPI_final_2020_dez.geojson"
out_html = "/n/netscratch/cga/Lab/rpalbuquerque/CPI/mapa_interativo_cpi_final_2020_dez.html"

# ============== PIPELINE ==============
print("📥 Loading CSV data...")
df = pd.read_csv(csv_path)

print("🧠 Computing CPI_final...")
df = compute_final_cpi(df)

print(f"💾 Saving final CPI to CSV → {out_csv}")
df.to_csv(out_csv, index=False)

print("🧩 Inserting CPI into GeoJSON...")
save_geojson_with_cpi(df, geojson_path, out_geojson)

print("🌍 Generating interactive map...")
generate_cpi_map(df, out_geojson, out_html)

print("✅ Pipeline completed.")